import 'dart:io';

/// Reads the API token from the runtime/data/api.token file.
/// The token is auto-generated by the backend on first boot.
///
/// Falls back gracefully — if the file doesn't exist, returns null
/// (the backend might have PECUNATOR_API_AUTH_DISABLED=1).
class ApiTokenReader {
  static String? _cachedToken;
  static DateTime? _lastRead;
  
  /// Re-read interval to pick up token regeneration.
  static const _cacheDuration = Duration(minutes: 5);

  /// Read the API bearer token from the filesystem.
  /// Returns null if the file is missing (auth may be disabled).
  static String? readToken() {
    final now = DateTime.now();
    if (_cachedToken != null && _lastRead != null &&
        now.difference(_lastRead!) < _cacheDuration) {
      return _cachedToken;
    }

    try {
      // Resolve path relative to the executable or working directory
      final candidates = [
        // When running from repo root
        File('runtime/data/api.token'),
        // When running built exe from desktop_shell
        File('../runtime/data/api.token'),
        // Absolute path (common dev setup)
        ...(_resolveFromScript()),
      ];

      for (final f in candidates) {
        if (f.existsSync()) {
          final token = f.readAsStringSync().trim();
          if (token.isNotEmpty) {
            _cachedToken = token;
            _lastRead = now;
            return token;
          }
        }
      }
    } catch (_) {}
    
    return _cachedToken; // Return last known good, or null
  }

  static List<File> _resolveFromScript() {
    try {
      // Try to find the project root from the executable path
      final exe = Platform.resolvedExecutable;
      var dir = Directory(exe).parent;
      // Walk up looking for runtime/data/api.token
      for (int i = 0; i < 6; i++) {
        final candidate = File('${dir.path}/runtime/data/api.token');
        if (candidate.existsSync()) return [candidate];
        dir = dir.parent;
      }
    } catch (_) {}
    return [];
  }
}
